# Generated by Django 5.2.8 on 2026-01-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='extra_roles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
