# Generated by Django 5.2.8 on 2026-01-18 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_incidentreport_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearcherRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, auto_created=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField()),
                ('orgSchool', models.CharField(max_length=255, blank=True, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='researcher_attachments/')),
                ('status', models.CharField(max_length=20, choices=[('pending','Pending'),('approved','Approved'),('rejected','Rejected')], default='pending')),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
