# Generated by Django 5.2.9 on 2026-01-20 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_researcherrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected'), ('Resolved', 'Resolved')], default='Pending', max_length=20),
        ),
    ]
