# Generated by Django 5.2.9 on 2026-01-22 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_cmsguide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentreport',
            name='suggested_critical_level',
        ),
    ]
