# Generated by Django 5.2.9 on 2026-01-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_incidentreport_suggested_critical_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='suggested_critical_level',
            field=models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], max_length=20, null=True),
        ),
    ]
