# Generated by Django 5.2.9 on 2026-01-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_incidentreport_suggested_critical_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='other_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
