# Generated by Django 5.2.8 on 2026-01-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_incidentreport_other_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('researcher', 'Researcher'), ('admin', 'Admin'), ('officer', 'Officer'), ('citizen', 'Citizen')], max_length=20, null=True),
        ),
    ]
