# Generated by Django 5.2.9 on 2026-01-31 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_incidentreport_assigned_officer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('needs_info', 'Needs Info'), ('rejected', 'Rejected'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='researcherrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
