# Generated by Django 5.2.8 on 2026-01-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_incidentreport_assigned_officer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvacuationCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('school', 'School'), ('covered_court', 'Covered Court'), ('multi_purpose_hall', 'Multi-Purpose Hall'), ('gymnasium', 'Gymnasium')], max_length=50)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('address', models.TextField(blank=True)),
                ('facilities', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('needs_info', 'Needs Info'), ('rejected', 'Rejected'), ('resolved', 'Resolved')], default='Pending', max_length=20),
        ),
    ]
