# Generated by Django 5.2.8 on 2026-01-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_evacuationcenter_alter_incidentreport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='evacuationcenter',
            name='contact',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='evacuationcenter',
            name='type',
            field=models.CharField(choices=[('school', 'School'), ('court', 'Court'), ('hall', 'Hall'), ('gymnasium', 'Gymnasium')], max_length=50),
        ),
    ]
