# Generated by Django 5.2.8 on 2026-01-31 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_evacuationcenter_contact_alter_evacuationcenter_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='evacuationcenter',
            name='barangay',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
