# Generated by Django 5.2.8 on 2026-02-01 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_incidentreport_status_and_more'),
        ('api', '0016_evacuationcenter_barangay'),
    ]

    operations = [
    ]
