# Generated by Django 6.0.1 on 2026-02-01 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_merge_20260201_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cmsguide',
            old_name='content',
            new_name='post_body',
        ),
        migrations.RenameField(
            model_name='cmsguide',
            old_name='title',
            new_name='post_title',
        ),
        migrations.RemoveField(
            model_name='cmsguide',
            name='category',
        ),
        migrations.RemoveField(
            model_name='cmsguide',
            name='views',
        ),
        migrations.AddField(
            model_name='cmsguide',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cmsguide',
            name='post_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cmsguide',
            name='post_type',
            field=models.CharField(choices=[('safety', 'Safety'), ('protocol', 'Protocol'), ('preparedness', 'Preparedness'), ('announcement', 'Announcement')], default='safety', max_length=50),
        ),
        migrations.AddField(
            model_name='cmsguide',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cmsguide',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_guides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cmsguide',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='CmsGuideAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='cms_guides/')),
                ('file_type', models.CharField(choices=[('image', 'Image')], default='image', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.cmsguide')),
            ],
        ),
    ]
