# Generated by Django 6.0.1 on 2026-02-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_passwordresetotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmsguideattachment',
            name='file',
        ),
        migrations.AlterField(
            model_name='cmsguideattachment',
            name='file_type',
            field=models.CharField(max_length=50),
        ),
    ]
