# Generated by Django 6.0.1 on 2026-02-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_cmsguideattachment_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsguideattachment',
            name='file_url',
            field=models.TextField(default='placeholder.jpg'),
            preserve_default=False,
        ),
    ]
