# Generated by Django 5.2.9 on 2026-02-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_customuser_supabase_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('needs_info', 'Needs Info'), ('rejected', 'Rejected'), ('resolved', 'Resolved'), ('archived', 'Archived')], default='pending', max_length=20),
        ),
    ]
