# Generated by Django 5.2.8 on 2026-02-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_incidentreport_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='supabase_uid',
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='staff_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
