# Generated by Django 6.0.1 on 2026-02-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_customuser_supabase_uid_customuser_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsguide',
            name='post_type',
            field=models.CharField(choices=[('advisory', 'Advisory'), ('announcement', 'Announcement'), ('guide', 'Guide')], default='advisory', max_length=50),
        ),
    ]
