# Generated by Django 6.0.1 on 2026-02-07 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_cmsguide_post_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('office_hours', models.CharField(blank=True, max_length=150)),
                ('address', models.TextField(blank=True)),
                ('map_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuickContactPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('hotline', 'Hotline'), ('landline', 'Landline'), ('mobile', 'Mobile')], max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=50)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='api.quickcontact')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
    ]
