# Generated by Django 5.2.9 on 2026-02-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_notification_notificationread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='cms_post_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
