# Generated by Django 5.2.9 on 2026-02-10 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_notification_cms_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationread',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read', to='api.notification'),
        ),
    ]
