# Generated by Django 5.2.8 on 2026-02-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_notificationread_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='reply_message',
            field=models.TextField(blank=True, help_text='Temporary reply from citizen when report needs info', null=True),
        ),
    ]