# Generated by Django 5.2.8 on 2026-02-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_incidentreport_needs_info_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='needs_info_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]