# Generated by Django 5.2.8 on 2026-02-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_incidentreport_needs_info_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='reply_image_url',
            field=models.TextField(blank=True, help_text='Optional URL for reply image (e.g., stored in Supabase)', null=True),
        ),
    ]