# Generated by Django 5.2.9 on 2026-02-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_incidentreport_reply_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='barangay',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='event',
            field=models.CharField(blank=True, choices=[('verified', 'Verified'), ('severity_changed', 'Severity Changed'), ('resolved', 'Resolved')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='incident_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='severity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='severity_from',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='severity_to',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
