# Generated by Django 5.2.9 on 2026-02-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_notification_barangay_notification_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
