# Generated by Django 5.2.9 on 2026-02-15 02:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_add_created_at_to_researcherrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentreport',
            name='accuracy_m',
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='category',
            field=models.CharField(choices=[('fire', 'Fire'), ('flood', 'Flood'), ('landslide', 'Landslide'), ('vehicular_accident', 'Vehicular Accident'), ('chemical_gas_leak', 'Chemical / Gas Leak'), ('fallen_tree', 'Fallen Tree'), ('infrastructure_damage', 'Infrastructure Damage'), ('earthquake', 'Earthquake'), ('typhoon', 'Typhoon'), ('others', 'Others')], max_length=30),
        ),
        migrations.AlterField(
            model_name='researcherrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 2, 15, 2, 3, 57, 188175, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
