# Generated by Django 5.2.9 on 2026-02-15 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_remove_incidentreport_accuracy_m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='flag_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
