# Generated by Django 5.2.9 on 2026-02-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_incidentreport_flag_reason_incidentreport_is_flagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='lgu_post',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
