# Generated by Django 5.2.9 on 2026-02-15 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_incidentreport_lgu_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentreport',
            name='lgu_post',
        ),
    ]
