# Generated by Django 5.2.9 on 2026-02-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_remove_incidentreport_lgu_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='lgu_post',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
