# Generated by Django 5.2.9 on 2026-02-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_incidentreport_lgu_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='category',
            field=models.CharField(choices=[('fire', 'Fire'), ('flood', 'Flood'), ('landslide', 'Landslide'), ('vehicular_accident', 'Vehicular Accident'), ('chemical_gas_leak', 'Chemical / Gas Leak'), ('fallen_tree', 'Fallen Tree'), ('infrastructure_damage', 'Infrastructure Damage'), ('earthquake', 'Earthquake'), ('typhoon', 'Typhoon'), ('others', 'Others')], max_length=50),
        ),
    ]
