# Generated by Django 5.2.9 on 2026-02-17 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_incidentreport_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='officer_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='resolution_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='status_from',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='status_to',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
