# Generated by Django 5.2.9 on 2026-02-17 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_notification_officer_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='report_barangay',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='report_category',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='report_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
