# Generated by Django 5.2.9 on 2026-02-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_notification_report_barangay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_resident_verified',
            field=models.BooleanField(default=False),
        ),
    ]
