# Generated by Django 5.2.9 on 2026-02-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_notification_target_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='barangay',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
