# Generated by Django 5.2.9 on 2026-02-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_customuser_barangay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('official', 'Official'), ('incident', 'Incident'), ('report', 'Report'), ('verification', 'Verification')], max_length=20),
        ),
    ]
