# Generated by Django 5.2.9 on 2026-02-21 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_alter_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='barangay',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='target_user',
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
