# Generated by Django 5.2.9 on 2026-02-21 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_remove_customuser_barangay_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='target_user',
        ),
    ]
