# Generated by Django 5.2.9 on 2026-02-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_rename_user_notification_target_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='barangay',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
