# Generated by Django 6.0.1 on 2026-02-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_customuser_barangay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcherrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='researcherrequest',
            name='email',
            field=models.EmailField(default='unknown@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researcherrequest',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
