# Generated by Django 6.0.1 on 2026-03-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_alter_passwordresetotp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcherrequest',
            name='attachment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
