# Generated by Django 5.2.9 on 2026-03-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_alter_researcherrequest_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='receive_community_announcements',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='receive_hazard_alerts',
            field=models.BooleanField(default=True),
        ),
    ]
