# Generated by Django 5.2.9 on 2026-03-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_customuser_receive_community_announcements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='alert_severity',
            field=models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10),
        ),
    ]
