# Generated by Django 6.0.1 on 2026-03-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_customuser_alert_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentverificationrequest',
            name='id_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
