# Generated by Django 6.0.1 on 2026-04-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_alter_residentverificationrequest_id_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcherrequest',
            name='middle_name',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
