# Generated by Django 5.2.8 on 2026-04-22 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_researcherrequest_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
