# Generated by Django 5.2.8 on 2026-04-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_notification_assigned_officer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('official', 'Official'), ('incident', 'Incident'), ('report', 'Report'), ('verification', 'Verification'), ('assigned', 'Assigned'), ('needs_info_reply', 'Needs Info Reply')], max_length=20),
        ),
    ]
