# Generated by Django 5.2.9 on 2026-05-14 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcherrequest',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
