import L from "leaflet";

export interface NDVILayerOptions {
  opacity?: number;
  bbox?: [number, number, number, number];
  year?: number;
  fromDate?: string;
  toDate?: string;
  maxCloud?: number;
}

// Cabuyao, Laguna - centered on municipality with key barangay coverage
const DEFAULT_BBOX: [number, number, number, number] = [121.06, 14.20, 121.18, 14.32];

/**
 * Creates and adds an NDVI (green index) image overlay for Cabuyao.
 * The image is generated by the backend Copernicus Process API proxy.
 */
export function createNDVILayer(map: L.Map, options: NDVILayerOptions = {}): L.LayerGroup {
  const layerGroup = L.layerGroup().addTo(map);
  const {
    opacity = 0.8,
    bbox = DEFAULT_BBOX,
    year,
    fromDate,
    toDate,
    maxCloud = 15,  // Lower cloud coverage for clearer vegetation imagery
  } = options;

  const controller = new AbortController();

  const queryParams = new URLSearchParams({
    bbox: bbox.join(","),
    maxCloud: String(maxCloud),
    cacheBust: String(Date.now()),
  });

  if (typeof year === "number") {
    queryParams.append("year", String(year));
  } else {
    if (fromDate) queryParams.append("from", fromDate);
    if (toDate) queryParams.append("to", toDate);
  }

  const imageUrl = `/api/satellite/ndvi/?${queryParams.toString()}`;

  const bounds: L.LatLngBoundsExpression = [
    [bbox[1], bbox[0]], // south-west (lat, lon)
    [bbox[3], bbox[2]], // north-east (lat, lon)
  ];

  fetch(imageUrl, { signal: controller.signal })
    .then(async (res) => {
      if (!res.ok) {
        const errorText = await res.text().catch(() => "");
        throw new Error(`NDVI request failed: ${res.status} ${res.statusText} ${errorText}`.trim());
      }
      const contentType = res.headers.get("content-type") || "";
      if (!contentType.includes("image/")) {
        const errorText = await res.text().catch(() => "");
        throw new Error(`NDVI response is not an image (${contentType}) ${errorText}`.trim());
      }
      return res.blob();
    })
    .then((blob) => {
      const objectUrl = URL.createObjectURL(blob);
      const imageOverlay = L.imageOverlay(objectUrl, bounds, {
        opacity,
        attribution: "© Copernicus Sentinel-2 NDVI",
        interactive: false,
      });

      imageOverlay.on("remove", () => URL.revokeObjectURL(objectUrl));
      imageOverlay.addTo(layerGroup).bringToFront();
    })
    .catch((err) => {
      if (err.name !== "AbortError") {
        console.error("NDVI layer failed to load:", err);
      }
    });

  layerGroup.on("remove", () => controller.abort());
  return layerGroup;
}
