import L from "leaflet";

export interface NDVILayerOptions {
  opacity?: number;
  bbox?: [number, number, number, number];
  year?: number;
  month?: number; // 1-12, requires year to be set. Selects clearest image for the month.
  fromDate?: string;
  toDate?: string;
  maxCloud?: number;
  imageWidth?: number;
  imageHeight?: number;
}

const API_URL = import.meta.env.VITE_API_URL;

// Cabuyao, Laguna (expanded to include Casile)
const DEFAULT_BBOX: [number, number, number, number] = [120.97, 14.14, 121.22, 14.36];


/**
 * Creates and adds an NDVI (green index) image overlay for Cabuyao.
 * The image is generated by the backend Copernicus Process API proxy.
 */
export function createNDVILayer(map: L.Map, options: NDVILayerOptions = {}): L.LayerGroup {
  const layerGroup = L.layerGroup().addTo(map);
  const {
    opacity = 0.8,
    bbox = DEFAULT_BBOX,
    year,
    month,
    fromDate,
    toDate,
    imageWidth = 1536,
    imageHeight = 1536,
  } = options;
  
  // Use higher cloud threshold to ensure images are found (especially for month-specific requests)
  // The backend uses leastCC mosaicking to still select the clearest available image
  const maxCloud = options.maxCloud ?? (month ? 50 : 30);

  const controller = new AbortController();

  const queryParams = new URLSearchParams({
    bbox: bbox.join(","),
    maxCloud: String(maxCloud),
    width: String(imageWidth),
    height: String(imageHeight),
    cacheBust: String(Date.now()),
  });

  if (typeof year === "number") {
    queryParams.append("year", String(year));
    // If month is specified (1-12), add it to get clearest image for that month
    if (typeof month === "number" && month >= 1 && month <= 12) {
      queryParams.append("month", String(month));
    }
  } else {
    if (fromDate) queryParams.append("from", fromDate);
    if (toDate) queryParams.append("to", toDate);
  }

  const imageUrl = `/api/satellite/ndvi/?${queryParams.toString()}`;

  const bounds: L.LatLngBoundsExpression = [
    [bbox[1], bbox[0]], // south-west (lat, lon)
    [bbox[3], bbox[2]], // north-east (lat, lon)
  ];

  // Add a loading indicator popup at the center of the bounds
  const center: L.LatLngExpression = [
    (bbox[1] + bbox[3]) / 2,
    (bbox[0] + bbox[2]) / 2,
  ];
  
  const loadingPopup = L.popup({
    closeButton: false,
    autoClose: false,
    closeOnClick: false,
    className: "ndvi-loading-popup",
  })
    .setLatLng(center)
    .setContent('<div style="padding: 12px; text-align: center;"><span>Loading Green Index...<br/></span></div>')
    .addTo(layerGroup);

  console.log("[NDVI] Fetching satellite image:", imageUrl);

  fetch(imageUrl, { signal: controller.signal })
    .then(async (res) => {
      if (!res.ok) {
        const errorText = await res.text().catch(() => "");
        console.error("[NDVI] API Error Response:", res.status, errorText);
        throw new Error(`NDVI request failed: ${res.status} ${res.statusText} - ${errorText}`.trim());
      }
      const contentType = res.headers.get("content-type") || "";
      if (!contentType.includes("image/")) {
        const errorText = await res.text().catch(() => "");
        console.error("[NDVI] Invalid content type:", contentType, errorText);
        throw new Error(`NDVI response is not an image (${contentType}) ${errorText}`.trim());
      }
      return res.blob();
    })
    .then((blob) => {
      // Remove loading popup on success
      loadingPopup.remove();
      
      const objectUrl = URL.createObjectURL(blob);
      const imageOverlay = L.imageOverlay(objectUrl, bounds, {
        opacity,
        attribution: "© Copernicus Sentinel-2 NDVI",
        interactive: false,
      });

      imageOverlay.on("remove", () => URL.revokeObjectURL(objectUrl));
      imageOverlay.addTo(layerGroup).bringToFront();
      console.log("[NDVI] Layer loaded successfully");
    })
    .catch((err) => {
      if (err.name !== "AbortError") {
        console.error("[NDVI] Layer failed to load:", err);
        // Show error in the popup
        loadingPopup.setContent(
          `<div style="padding: 8px; text-align: center; color: #c00; max-width: 250px;">
            <strong>Green Index Error</strong><br/>
            <span style="font-size: 12px;">${err.message || "Failed to load satellite imagery"}</span>
          </div>`
        );
      }
    });

  layerGroup.on("remove", () => controller.abort());
  return layerGroup;
}
